"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import * as apiService from "@/services/apiService";
import { Room } from "@/types";
import { PrimaryButton } from "@/components/PrimaryButton";
import { TextInput } from "@/components/TextInput";
import { RoomCard } from "@/components/RoomCard";
import { Divider } from "@/components/Divider";
import { getUsername } from "@/utils/auth";
import Navbar from "@/components/Navbar";
import { toast } from "sonner";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { TooltipArrow } from "@radix-ui/react-tooltip";

export default function Home() {
  const [rooms, setRooms] = useState<Room[]>([]);
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);
  const [joining, setJoining] = useState(false);
  const [newRoomName, setNewRoomName] = useState("");
  const [isNewRoomPublic, setIsNewRoomPublic] = useState<boolean>(true);
  const [joinRoomName, setJoinRoomName] = useState("");
  const [roomsPageNumber, setRoomsPageNumber] = useState<number>(0);
  const [hasMoreRooms, setHasMoreRooms] = useState<boolean>(true);

  // CITATION
  // this code was generated by AI (Claude)
  // prompt: Why am i getting this console error on the landing page [Error] Warning: Expected server HTML to contain a matching <div> in <div>.
  const [mounted, setMounted] = useState(false);
  // END CITATION

  const router = useRouter();

  const ROOMS_PER_PAGE = 10;

  const fetchRoomsData = async () => {
    if (!hasMoreRooms) return;
    try {
      const roomsReponse = await apiService.fetchRooms(
        ROOMS_PER_PAGE,
        roomsPageNumber * ROOMS_PER_PAGE,
      );
      setRooms([...rooms, ...roomsReponse.rooms]);
      setHasMoreRooms(roomsReponse.hasMore);
      setRoomsPageNumber(roomsPageNumber + 1);
    } catch (error) {
      console.log("could not fetch rooms");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    // CITATION
    // this code was generated by AI (Claude)
    // prompt: Why am i getting this console error on the landing page [Error] Warning: Expected server HTML to contain a matching <div> in <div>.
    setMounted(true);
    if (typeof document !== "undefined") {
      document.body.style.overflow = "auto"; // allow scrolling
    }
    if (!getUsername()) {
      router.push("/auth");
      return;
    }
    // END CITATION
    fetchRoomsData();
  }, []);

  const createRoom = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!newRoomName.trim()) return;
    setCreating(true);
    try {
      const data = await apiService.createRoom(
        newRoomName.trim(),
        isNewRoomPublic,
      );
      setNewRoomName("");
      router.push(`/room/${data.code}`);
    } catch (err) {
      console.error("create room error", err);
    } finally {
      setCreating(false);
    }
  };

  const joinRoom = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!joinRoomName.trim()) return;
    setJoining(true);
    try {
      await apiService.fetchRoom(joinRoomName.trim());
      router.push(`/room/${joinRoomName}`);
    } catch (error) {
      let errorMsg = "";
      if (error instanceof Error) {
        errorMsg = ": " + error.message;
      }
      toast.error(`error joining room${errorMsg}`, {
        closeButton: true,
      });
    } finally {
      setJoining(false);
    }
  };

  // CITATION
  // this code was generated by AI (Claude)
  // prompt: Why am i getting this console error on the landing page [Error] Warning: Expected server HTML to contain a matching <div> in <div>.
  if (!mounted) {
    return null;
  }

  if (!getUsername()) {
    return null;
  }
  // END CITATION

  return (
    <div className="min-h-screen bg-zinc-50 p-8">
      <div className="max-w-6xl mx-auto">
        <div className="mb-12">
          <Navbar />

          <h2 className="text-3xl text-indigo-950 mb-10 font-medium">
            {"Welcome, " + getUsername() + "!"}
          </h2>

          <form onSubmit={createRoom} className="flex gap-3 items-center mt-4">
            <TextInput
              value={newRoomName}
              placeholder="Room name"
              onChange={setNewRoomName}
              className="w-4/6"
            />
            <PrimaryButton
              buttonType="submit"
              label={creating ? "Creating..." : "Create Room"}
              isDisabled={creating}
              className="w-1/6"
            />

            <Tooltip>
              <TooltipTrigger asChild>
                <label className="w-1/6 flex items-center h-full gap-2 text-gray-500 font-medium">
                  <input
                    type="checkbox"
                    checked={isNewRoomPublic}
                    onChange={(e) => setIsNewRoomPublic(e.target.checked)}
                  ></input>
                  <p>Make it public?</p>
                </label>
              </TooltipTrigger>
              <TooltipContent className="bg-white text-black">
                <TooltipArrow className="fill-white" />
                <div className="flex flex-col gap-1 items-center justify-center">
                  <p>Public rooms show up on the home page</p>
                  <p>Private rooms can only be accessed using their code</p>
                </div>
              </TooltipContent>
            </Tooltip>
          </form>

          <Divider />

          <form onSubmit={joinRoom} className="flex gap-3 items-center mt-4">
            <TextInput
              value={joinRoomName}
              placeholder="Room code"
              onChange={setJoinRoomName}
              className="w-5/6"
            />
            <PrimaryButton
              buttonType="submit"
              label={joining ? "Joining..." : "Join Room"}
              isDisabled={joining}
              className="w-1/6"
            />
          </form>
        </div>

        {loading && (
          <div className="text-center py-12">
            <p className="text-xl text-indigo-800">Loading rooms...</p>
          </div>
        )}

        {!loading && rooms.length === 0 && (
          <div className="bg-white rounded-lg shadow-md p-12 text-center">
            <h2 className="text-2xl font-semibold text-indigo-900 mb-4">
              No Public Rooms
            </h2>
            <p className="text-indigo-700 mb-6">
              There are currently no public rooms. Create one or join one to get
              started!
            </p>
          </div>
        )}

        {!loading && rooms.length > 0 && (
          <div className="flex flex-col justify-center">
            <h2 className="text-3xl font-bold text-indigo-900 mb-8">
              Public Rooms
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {rooms.map((room) => (
                <RoomCard key={room.code} room={room} />
              ))}
            </div>
            <div className="flex w-full justify-center items-center">
              <Tooltip>
                <TooltipTrigger asChild>
                  <button
                    onClick={() => fetchRoomsData()}
                    className="disabled:bg-gray-500 disabled:text-gray-700 disabled:cursor-not-allowed m-10 bg-indigo-900 text-white font-semibold px-4 py-2 rounded-full w-3/12"
                    disabled={!hasMoreRooms}
                  >
                    Show more
                  </button>
                </TooltipTrigger>
                <TooltipContent className="bg-white text-black">
                  <TooltipArrow className="fill-white" />
                  <p>
                    {hasMoreRooms
                      ? "Load more rooms"
                      : "No more rooms. Go create one!"}
                  </p>
                </TooltipContent>
              </Tooltip>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
